# Generated by Django 4.2.4 on 2023-09-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rfinv_loc',
            fields=[
                ('Loc_ID', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('Loc_Name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('Loc_ID',),
            },
        ),
        migrations.CreateModel(
            name='rfinv_inv',
            fields=[
                ('Inv_ID', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('Inv_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Inv_Last_Check_Time', models.DateTimeField(auto_now_add=True)),
                ('Inv_Last_Loc', models.CharField(blank=True, max_length=255, null=True)),
                ('Loc_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InvLocationID', to='core.rfinv_loc')),
            ],
            options={
                'ordering': ('Inv_ID',),
            },
        ),
        migrations.CreateModel(
            name='rfinv_check',
            fields=[
                ('Chk_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Chk_Time', models.DateTimeField(auto_now_add=True)),
                ('Inv_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChkInventoryID', to='core.rfinv_inv')),
                ('Loc_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChkLocationID', to='core.rfinv_loc')),
            ],
            options={
                'ordering': ('Chk_ID',),
            },
        ),
    ]
