# Generated by Django 5.0.2 on 2024-03-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="rfinv_loc",
            fields=[
                (
                    "Loc_ID",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("Loc_Name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "ordering": ("Loc_ID",),
            },
        ),
        migrations.CreateModel(
            name="rfinv_inv",
            fields=[
                (
                    "Inv_ID",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("Inv_Name", models.CharField(blank=True, max_length=255, null=True)),
                ("Inv_Created", models.DateTimeField(auto_now_add=True)),
                ("Inv_Modified", models.DateTimeField(auto_now=True)),
                ("Inv_Last_Check_Time", models.DateTimeField(auto_now_add=True)),
                (
                    "Inv_Last_Loc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Loc_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Inv_Location",
                        to="rvapi.rfinv_loc",
                    ),
                ),
            ],
            options={
                "ordering": ("Inv_ID",),
            },
        ),
        migrations.CreateModel(
            name="rfinv_check",
            fields=[
                (
                    "Chk_ID",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("Chk_Time", models.DateTimeField(auto_now_add=True)),
                (
                    "Inv_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Chk_Inv",
                        to="rvapi.rfinv_inv",
                    ),
                ),
                (
                    "Loc_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Chk_Location",
                        to="rvapi.rfinv_loc",
                    ),
                ),
            ],
            options={
                "ordering": ("Chk_ID",),
            },
        ),
    ]
