# Generated by Django 5.0.2 on 2024-03-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rvapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfinv_inv",
            name="RFCode",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rfinv_inv",
            name="Inv_ID",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
