# Generated by Django 5.0.7 on 2024-08-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rvapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rfidtag',
            table=None,
        ),
    ]
