# Generated by Django 5.0.7 on 2024-08-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rvapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectiontag',
            name='inspection',
        ),
        migrations.RemoveField(
            model_name='inspectiontag',
            name='rfid_tag',
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ('rfid_tag',)},
        ),
        migrations.AlterModelOptions(
            name='rfidtag',
            options={'ordering': ('RFID',)},
        ),
        migrations.AlterModelTable(
            name='inventory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='location',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rfidtag',
            table=None,
        ),
        migrations.DeleteModel(
            name='Inspection',
        ),
        migrations.DeleteModel(
            name='InspectionTag',
        ),
    ]
