# Generated by Django 5.0.2 on 2026-02-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='found_inventories',
            field=models.ManyToManyField(blank=True, related_name='inspections', to='rvapi.inventory'),
        ),
    ]
