# Generated by Django 5.0.2 on 2024-03-01 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rvapi", "0002_rfinv_inv_rfcode_alter_rfinv_inv_inv_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rfinv_inv",
            name="Loc_ID",
        ),
    ]
